apiVersion: kraan.io/v1alpha1
kind: AddonsLayer
metadata:
  name: podinfo
spec:
  version: 1.0.0
  interval: 1m
  source:
    name: podinfo
    namespace: default
    path: ./helm-releases
  prereqs:
    k8sVersion: "1.16"
